#!/bin/sh

# source/parser - parses and stitches the markdown file

# import for handle_h
. source/handle/h

parser() {
    # Copy the header over to start the file
    mkdir -pv ${f_final_dest%/*} # removes filename
    cp -v "$f_type_loc/template_header" "$f_final_dest"

    while IFS= read -r l || [ -n "$l" ]
    do
        [ -z "$l" ] && continue
        # Discard first line in the file if it's a type line
        [ "$l" = "$f_1l" ] && continue
    
        # echo "$l"
    
        # Checking for h* of any number in the beginning
        l_test=$(printf '%s' "$l" | grep -E '^#+')
        [ -n "$l_test" ] && handle_h && continue
        
        # Custom elements
        # l_test="$(printf '%s' "$l" | grep -o '^\$\w*:::..')"
        # [ -n "$l_test" ] && handle_special && continue
    
        # No type, it's a p
        # handle_p
    done < "$f"

    cat "$f_type_loc/template_footer" >> "$f_final_dest"
}
